#!/bin/sh
#
# CherryMusic - a standalone music server
# Copyright (c) 2012 Tom Wallroth & Tilman Boerner
#
# Project page:
#   http://fomori.org/cherrymusic/
# Sources on github:
#   http://github.com/devsnd/cherrymusic/
#
# CherryMusic is based on
#   jPlayer (GPL/MIT license) http://www.jplayer.org/
#   CherryPy (BSD license) http://www.cherrypy.org/
#
# licensed under GNU GPL version 3 (or later)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>
#
##############################################################################
#
# git pre-commit hook. place an executable link to this file into .git/hooks to 
# execute automatically check and verify the git index before each commit.
#
##############################################################################

echo "executing pre-commit hook: $0"

gitroot=`git rev-parse --show-toplevel`
testrunner=${gitroot}/update_website.py
if [ ! -f ${testrunner} -o ! -x ${testrunner} ]; then
    echo "error: cannot find testrunner script: ${testrunner}" >&2
    exit 1
fi

python ${testrunner}
